# Use an official lightweight web server image
FROM nginx:alpine

# Copy your dashboard files into the nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80 to access the web app
EXPOSE 80
