openapi: 3.0.0

info:
  title: Online Quiz Platform API
  description: A simple API to create quizzes and questions
  contact:
    email: nastaranzirak717@gmail.com
  version: 1.0.0
paths:
  /quiz/create:
    post:
      summary: Create a quiz
      description: Creates a new quiz with a name and description
      operationId: app.create_quiz
      requestBody:
        description: Quiz details to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        "201":
          description: Quiz created successfully
        "400":
          description: Invalid input, object invalid
  /questions/create:
    post:
      summary: Add a question
      description: Adds a new question to a quiz
      operationId: app.create_question
      requestBody:
        description: Question details to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        "201":
          description: Question added successfully
        "400":
          description: Invalid input, object invalid
components:
  schemas:
    Quiz:
      type: object
      required:
        - name
        - description
        - time_limit
        - timestamp
      properties:
        name:
          type: string
          description: The name of the quiz
          example: test1
        description:
          type: string
          description: The description of the quiz
          example: quiz one
        time_limit:
          type: integer
          description: The tine limit for completing the quiz
          example: 30
        timestamp:
          type: string
          format: date-time
          description: The date and time when the quiz was created
          example: 2025-01-22T10:00:00Z
    Question:
      type: object
      required:
        - exam_id
        - text
        - order
        - correct_answer
        - score
        - timestamp
      properties:
        exam_id:
          type: integer
          description: The ID of the quiz the question belongs to
          example: 1
        text:
          type: string
          description: The text of the question
          example: "Name an animal that starts with a 'T'."
        order:
          type: integer
          description: The order of the question in the quiz
          example: 1
        correct_answer:
          type: string
          description: The correct answer to the question
          example: Turtle
        score:
          type: number
          format: float
          description: The score of the question
          example: 0.5
        timestamp:
          type: string
          description: The date and time when the question was added
          example: 2025-01-22T10:05:00Z